### ISSUE TITLE
.git Not a git repository

### ISSUE THREAD

**Issue by valentin2105** [pieterlange/kube-backup#18]
Hi !

I try to use kube-backup to backup my k8s cluster and push in my Private Gitlab instance,

I use the `cronjob ssh` ressource and created the `kube-backup-ssh` secret from an allowed ssh key. 

When the pod is created, I follow the logs, it fetch all ressources and before finish, I got theses errors : 

```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

Any idea where I'm wrong ? 

```
            - name: GIT_REPO
              value: "git.private.com:Kubernetes/dev-cluster-rancid.git"
            - name: GIT_USERNAME
              value: "git"
            - name: RESOURCETYPES
              value: "ingress deployment configmap svc rc ds thirdpartyresource networkpolicy statefulset storageclass cronjob"
            volumeMounts:
            - mountPath: /backup/
              name: cache
            - mountPath: /backup/.ssh
              name: sshkey
```

**Comment by pieterlange** [comment]
can you post the full deployment spec please?

**Comment by valentin2105** [comment]
Sure,

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: kube-state-backup
  namespace: kube-system
  labels:
    app: kube-backup
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kube-backup
          name: kube-backup
        spec:
          containers:
          - image: ptlange/kube-backup:1.5.4
            imagePullPolicy: Always
            name: backup
            resources: {}
            env:
            - name: GIT_REPO
              value: "mygitlab.com:Kubernetes/dev-cluster-rancid.git"
            - name: GIT_USERNAME
              value: "git"
            - name: RESOURCETYPES
              value: "ingress deployment configmap svc rc ds thirdpartyresource networkpolicy statefulset storageclass cronjob"
            volumeMounts:
            - mountPath: /backup/
              name: cache
            - mountPath: /backup/.ssh
              name: sshkey
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 30
          serviceAccountName: kube-backup
          volumes:
          - name: sshkey
            secret:
              defaultMode: 420
              secretName: kube-backup-ssh
          - name: cache
            emptyDir: {}
          restartPolicy: OnFailure


```
