### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by zeusro** [pieterlange/kube-backup#59]
Cloning into '/backup/git'...
load pubkey "/backup/.ssh/id_rsa": Permission denied
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into '/backup/git'...
load pubkey "/backup/.ssh/id_rsa": Permission denied
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zeusro** [comment]
I have already mount the ssh secret but it seem the "backup" user have no permission to read `/backup/.ssh`

**Comment by zeusro** [comment]
```yaml
          volumes:
          - name: cache
            emptyDir: {}
          - name: sshkey
            secret:           
             secretName: xxx
             defaultMode: 0420
```

**Comment by zeusro** [comment]
Please make sure you have the correct access rights
and the repository exists.
Cloning into '~/git'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0420 for '/root/.ssh/id_rsa' are too open.

**Comment by zeusro** [comment]
Have you ever tested it on your own kubernetes cluster ?

**Comment by davidkarlsen** [comment]
I have:
```
    volumeMounts:
              - mountPath: /backup/
                name: cache
              - mountPath: /backup/.ssh
                name: sshkey
              - mountPath: /secrets
                name: gpgkey
            dnsPolicy: ClusterFirst
            nodeSelector:
              fs.evry.com/finods-group: aot
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: kube-backup
            serviceAccountName: kube-backup
            terminationGracePeriodSeconds: 30
            volumes:
            - name: sshkey
              secret:
                defaultMode: 420
                secretName: kube-backup-ssh
            - name: gpgkey
```

which works fine
